In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
X = df.drop(['species'], axis=1)
y = df['species']

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_test, X_train, y_test, y_train = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [48]:
model_knn = KNeighborsClassifier(n_neighbors=3)

In [49]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [50]:
model_knn.score(X_test, y_test)

0.9416666666666667

# Grid Search CV

In [51]:
from sklearn.model_selection import GridSearchCV

In [53]:
classifier = GridSearchCV(estimator=model_knn, param_grid={'n_neighbors': [1, 3, 5, 7, 9]}, cv=5,return_train_score=True)

In [54]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9]},
             return_train_score=True)

In [55]:
classifier.cv_results_

{'mean_fit_time': array([0.00350204, 0.00265465, 0.00409703, 0.00389376, 0.00459547]),
 'std_fit_time': array([0.0010084 , 0.00043843, 0.00204045, 0.00076328, 0.00131102]),
 'mean_score_time': array([0.00468936, 0.00382433, 0.00550528, 0.00587888, 0.00786872]),
 'std_score_time': array([0.00156726, 0.00030871, 0.00347367, 0.0018078 , 0.00236568]),
 'param_n_neighbors': masked_array(data=[1, 3, 5, 7, 9],
              mask=[False, False, False, False, False],
        fill_value=999999),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 3},
  {'n_neighbors': 5},
  {'n_neighbors': 7},
  {'n_neighbors': 9}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.96666667, 0.96666667]),
 'split3_test_score': array([0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96666667, 0.97333333, 0.98      , 0.97333333]),
 'std_test_score': array([0.02494438, 0.02108185, 0.02494438, 0.01632993, 0.02494438]),
 'rank_test_score': array([5, 4, 2, 1, 2], dtype=int32),
 'split0_train_score': array([1.        , 0.95833333, 0.96666667, 0.96666667, 0.975     ]),
 'split1_train_score': array([1.        , 0.95833333, 0.96666667, 0.96666667, 0.98333333]),
 'split2_train_score': array([1.        , 0.96666667, 0.975     , 0.975     , 0.975     ]),
 'split3_train_score': array([1.        , 0.96666667, 0.975     , 0.98333333, 0.98333333]),
 'split4_train_score': array([1.        , 0.95      , 0.96666667, 0.975     , 0.975     ]),
 'mean_train_score': array([1.        , 0.96      , 0.97      , 0.97333333, 0.97833333]),
 'std_train_score': array([0.        , 0.0062361 , 0.00408248, 0.0062361 , 0.00408248])}

In [56]:
res = pd.DataFrame(classifier.cv_results_)

In [57]:
res

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,0.003502,0.001008,0.004689,0.001567,1,{'n_neighbors': 1},0.966667,0.966667,0.933333,0.933333,...,0.960000,0.024944,5,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
1,0.002655,0.000438,0.003824,0.000309,3,{'n_neighbors': 3},0.966667,0.966667,0.933333,0.966667,...,0.966667,0.021082,4,0.958333,0.958333,0.966667,0.966667,0.950000,0.960000,0.006236
2,0.004097,0.002040,0.005505,0.003474,5,{'n_neighbors': 5},0.966667,1.000000,0.933333,0.966667,...,0.973333,0.024944,2,0.966667,0.966667,0.975000,0.975000,0.966667,0.970000,0.004082
3,0.003894,0.000763,0.005879,0.001808,7,{'n_neighbors': 7},0.966667,1.000000,0.966667,0.966667,...,0.980000,0.016330,1,0.966667,0.966667,0.975000,0.983333,0.975000,0.973333,0.006236
4,0.004595,0.001311,0.007869,0.002366,9,{'n_neighbors': 9},0.966667,1.000000,0.966667,0.933333,...,0.973333,0.024944,2,0.975000,0.983333,0.975000,0.983333,0.975000,0.978333,0.004082

In [58]:
res[['param_n_neighbors', 'mean_test_score']]

   param_n_neighbors  mean_test_score
0                  1         0.960000
1                  3         0.966667
2                  5         0.973333
3                  7         0.980000
4                  9         0.973333

# Random search CV

In [59]:
from sklearn.model_selection import RandomizedSearchCV

In [60]:
random_classifier = RandomizedSearchCV(model_knn, param_distributions={'n_neighbors': [1, 3, 5, 7, 9]}, cv=5, n_iter=3, return_train_score=True)

In [61]:
random_classifier.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=3),
                   n_iter=3,
                   param_distributions={'n_neighbors': [1, 3, 5, 7, 9]},
                   return_train_score=True)

In [62]:
result_random = pd.DataFrame(random_classifier.cv_results_)

In [64]:
result_random[['param_n_neighbors', 'mean_test_score']]

   param_n_neighbors  mean_test_score
0                  5         0.966667
1                  7         0.966667
2                  3         0.933333